### ISSUE TITLE
old version of the site

### ISSUE THREAD

**Issue by amrayoub** [jsonberry/learn-reactive#10]
Where can I find old version on the site https://pentacledev.com .
There were some great articles and Reactive programming principles ?

**Comment by jsonberry** [comment]
Hey @amrayoub thanks for reaching out

All of the articles that were on pentacle were moved to https://learnreactive.com and you can find them alongside new ones.

As for the other content like the principles, that was work that I wrote up and I pulled it out to be used in blog posts instead of being up on the site.

I have the content still, and I don't have them ready for publishing yet. Here's a snippet from the reactive principles overview hope that helps for now until the articles are published:

# Declare What Instead of How
- In an ideal Reactive system, only what is required needs to be specified, not how the requirements are to be accomplished. Writing code in a specific declarative way and using already available tools achieves this.
# Restrict Each Module to One Purpose
- Each Module is the expert on its specific responsibility. This means it should have a nearly singular purpose. Other Modules should not also be responsible for the same purpose in the system. This is also called the Single Responsibility Principle (SRP).
# Think of Everything as a Stream
- Treat all events as the same shaped thing, traveling down a stream. When everything is the same shape, it becomes very easy to combine and merge and query those things resulting in a very powerful tool.
# Don’t Store What You Can Derive
- Information is obtained from already established data. If data can be computed from an existing source, it is not stored. This shifts the preference from storing computed values to making derivations convenient.
# Flow Data in One Direction 
- To support predictability, data flows between Modules in only one direction.

**Comment by amrayoub** [comment]
Any idea where can I get the full content that were on pentacledev.com ?
