### ISSUE TITLE
New Resource Request

### ISSUE THREAD

**Issue by Fallenstedt** [jsonberry/learn-reactive#9]
### Required Attributes
- origin_title: **A Super Ninja Trick To Learn RxJS’s “switchMap”, “mergeMap”, “concatMap” and “exhaustMap”, FOREVER! 😎**
- author: Shai Reznik
- cost: false
- tags: rxjs, Functional Reactive Programming
- difficulty: introductory
- format: video && article
- source: https://medium.com/@shairez/a-super-ninja-trick-to-learn-rxjss-switchmap-mergemap-concatmap-and-exhaustmap-forever-88e178a75f1b

### Optional Attributes
- title: Learn switchMap, mergeMap, concatMap, exhaustMap forever.
- social: https://twitter.com/shai_reznik?lang=en

### Summary
Remembering what flattening strategy you need when juggling many observables can be a daunting task. Shai and his team of expert reactive programmers present a fun and clever way to remember switchMap, mergeMap, concatMap, and exhaustMap forever. This is a must watch for those starting to learn RxJS and those needing to teach RxJS.

**Comment by jsonberry** [comment]
@Fallenstedt 

The data model isn't set up to denote a resource as being multiple types, so the easiest thing will be to post this as either an article or a video.

Do you feel this would be better as the article or the video? which one did you get more out of?

I could post it as a video and have a link to the article in the summary, that sound like a good deal?

**Comment by Fallenstedt** [comment]
I would say article because there is more info in there. The video only
covers switchMap, but article forces you watch the video before continuing.

**Comment by jsonberry** [comment]
Alright sounds good mate, and I'm going to mark this as an intermediate difficulty because I think usually when someone is at the very beginning of their working Rx knowledge flattening operators generally aren't involved yet. I still need to port those defs into learnreactive.com I think I'll do a hover tooltip thing again, and also probably add these to the issue template:

- introductory: You're brand new to this topic, you want to see what it's all about.
- beginner: You have an idea of what this is about, but you're still at the very beginning of your working knowledge.
- intermediate: You're able to adapt and apply the basic knowledge to solve new challenges, and you're ready to learn more.
- advanced: You're well beyond the basics, you've worked with this enough to have solved some difficult challenges, and you're ready for advanced concepts.

**Comment by Fallenstedt** [comment]
💯
